FROM nodered/node-red:latest
USER root
RUN npm install node-red-dashboard
RUN npm install node-red-node-mysql
RUN npm install node-red-contrib-influxdb
RUN npm install node-red-contrib-telegrambot
RUN npm i node-red-node-ui-list
USER node-red